Migrate to react-leaflet v3 (redo)
clementallen/react-leaflet-textpath pull request #50
Opened 2021-01-16 01:59 UTC by MasterEric

Had to recreate the pull request since I realized the original PR was trying to merge the wrong branch.

Compared to #49:

* getOptions has been cleared away, making the code related to parameters simpler.
* I removed the component test since react-leaflet no longer uses the components as children.
* I added a note to the test that was failing because of PaulLeCam/react-leaflet#830.

2021-01-16 12:08 UTC, clementallen requested changes
Looks good!  Just a few unused lines that can be removed.

I'm keen to not merge this to master until the issue around updating the component has been resolved.  I can either keep the MR open or merge it to a separate branch now and make any further changes myself later on, what would you prefer?

2021-01-16 12:08 UTC, clementallen commented on src/index.js
> +// eslint-disable-next-line no-unused-vars
Linting passes for me with this comment removed

2021-01-16 12:08 UTC, clementallen commented on src/index.js
> +    // const { positions, options, text, ...pathOptions } = getOptions(props);
Can this be removed please as no longer needed?

2021-01-16 12:08 UTC, clementallen commented on src/index.js
> +// eslint-disable-next-line no-unused-vars
Linting passes for me with this comment removed

2021-01-17 09:48 UTC, MasterEric commented
> I can either keep the MR open or merge it to a separate branch now and make any further changes myself later on, what would you prefer?

I think the latter makes more sense to me (merging into a branch pending the upstream fix).

Thanks for your help in reviewing this PR! It's greatly appreciated. I hope the issue gets resolved soon.

2021-01-17 15:35 UTC, clementallen approved these changes

2021-01-17 15:38 UTC, clementallen commented
All looks good to me, thanks again for helping with this @MasterEric!

I'll update #48 once this is published pending any potential changes in react-leaflet itself

2021-01-17 15:38 UTC, merged

2021-01-21 02:22 UTC, nemosmithasf commented
I'm using this version right now, and it seems like the `below` attribute doesn't work.

2021-01-21 10:12 UTC, clementallen commented
Hi @nemosmithasf - I've just tested the `below` parameter locally and it works fine with this version.  Can you share some example code of how you're using the library and what you're expecting?

2021-01-21 11:56 UTC, nemosmithasf commented
Here's the code I'm using, I'm expecting the text to switch between the top/bottom of the line when I toggle "shouldFlipText" (similar to if I multiplied offset by -1)
```

    const bearing = calcBearing(currCoordinate, endCoordinate);
    const shouldFlipText = 0 > bearing;

    return (
      <TextPath_baseComponent
        positions={[[currCoordinate, endCoordinate]]}
        color={"transparent"}
        text={text}
        center
        offset={20}
        below={shouldFlipText} 
        orientation={shouldFlipText ? "flip" : 0}
        attributes={{
          "font-size": fontSize,
          opacity: textOpacity,
          fill: fontColor,
          "font-weight": fontWeight,
          ...attributes,
        }}
      />
    );
```

2021-01-21 11:59 UTC, clementallen commented
@nemosmithasf the `below` attribute actually controls whether the text sits below or above the line in terms of z-index, not positioning.  To achieve what you're wanting you can set the offset to either be `-20` or `20` I think

2021-01-21 12:01 UTC, clementallen commented
I wasn't going to publish the new v3 support to NPM until PaulLeCam/react-leaflet#830 was resolved, but if it would help you I can publish it as a beta version?

2021-01-21 13:49 UTC, nemosmithasf commented
Ah, of course, when you put it that way, it makes a lot of sense.

As for v3; it depends on how much work it's for you; I've hacked together a working version so I can just set a reminder to check back in a few weeks when you're fully satisfied with the v3 version. No point adding extra work for you unless it's trivial.

2021-01-21 18:42 UTC, clementallen commented
@nemosmithasf I agree, it is a bit confusing - took me a few minutes to remember what it did myself!

No problem at all to publish a pre-release version, I've done it now.  You can install by running `npm install --save react-leaflet-textpath@next`

Hope that helps

2021-01-21 18:58 UTC, nemosmithasf commented
Appreciate it, and thanks for the good work

2021-01-24 22:24 UTC, clementallen commented
@nemosmithasf - no luck in the issue getting resolved in react-leaflet so will just have to accept it!  I've now published the v3 support as `2.0.0`

2021-01-25 00:05 UTC, nemosmithasf commented
thanks!