Ported the library to TypeScript.
clementallen/react-leaflet-textpath pull request #53
Opened 2021-03-17 20:20 UTC by MasterEric

I am using this in a TypeScript project. I was going to work on adding types via DefinitelyTyped, but I noticed that the library was small, so I decided to simply port the project to include builtin type definitions.

2021-04-01 22:42 UTC, clementallen requested changes

2021-04-01 22:42 UTC, clementallen commented
Thanks for this!  Migrating to Typescript is something I'd been thinking of doing for a while.

Can you please get the travis build working?  I'll then give it a test out myself and merge

2021-04-22 18:06 UTC, MasterEric commented on package.json
> +        "build": "yarn run build:clean && yarn run build:cjs && yarn run build:esm && yarn run build:types",
Done.

2021-06-21 18:08 UTC, clementallen commented
Thanks!  Sorry it took me so long to get to this, I've tested now and worked nicely.  Will merged now and publish as 2.1.0

2021-06-21 18:08 UTC, merged